/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

/**
 *
 * @author Miguel
 */
public class Pantallagato extends javax.swing.JFrame {
    int matrix[][] =new int [3][3];
    /**
     * Creates new form Pantallagato
     */
    public Pantallagato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Juego del Gato");
        jLabel1.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText(" ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText(" ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText(" ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setText(" ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setText(" ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText(" ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setText(" ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Inicial Juego");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jButton1.getText()==" ")        
        {        
            
            jButton1.setText("X");         
            matrix[0][0]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 0,0 ya usada");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jButton2.getText()==" ")        
        {            
            jButton2.setText("X");         
            matrix[0][1]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 0,1 ya usada");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jButton3.getText()==" ")        
        {            
            jButton3.setText("X");         
            matrix[0][2]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 0,2 ya usada");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jButton4.getText()==" ")        
        {            
            jButton4.setText("X");         
            matrix[1][0]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 1,0 ya usada");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jButton5.getText()==" ")        
        {            
            jButton5.setText("X");         
            matrix[1][1]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 1,1 ya usada");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jButton6.getText()==" ")        
        {            
            jButton6.setText("X");         
            matrix[1][2]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 1,2 ya usada");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jButton7.getText()==" ")        
        {            
            jButton7.setText("X");         
            matrix[2][0]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 3,0 ya usada");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jButton8.getText()==" ")        
        {            
            jButton8.setText("X");         
            matrix[2][1]=1;           
            checarJugada();            
            tiraMaquina();         
        }else  jTextField1.setText("Posición de la matriz 3,1 ya usada");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jButton9.getText()==" ")        
        {            
            jButton9.setText("X");         
            matrix[2][2]=1;           
            checarJugada();            
            tiraMaquina();         
        }else jTextField1.setText("Posición de la matriz 3,2 ya usada");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //iniciar juego
        jButton1.setText(" "); jButton2.setText(" "); jButton3.setText(" ");
        matrix[0][0]=0;       matrix[0][1]=0;       matrix[0][2]=0;
        jButton4.setText(" "); jButton5.setText(" "); jButton6.setText(" ");
        matrix[1][0]=0;       matrix[1][1]=0;       matrix[1][2]=0;
        jButton7.setText(" "); jButton8.setText(" "); jButton9.setText(" ");
        matrix[2][0]=0;       matrix[2][1]=0;       matrix[2][2]=0;
        jTextField1.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed
private void tiraMaquina(){ 
 //mover las jugadas, no usando ramdom         
int ban=0;
if((matrix[0][0]==0 && matrix[0][1]==1 && matrix[0][2]==1) || (matrix[0][0]==0 && matrix[1][0]==1 && matrix[2][0]==1) || (matrix[0][0]==0 && matrix[1][1]==1 && matrix[2][2]==1))//0.0
 {
jButton1.setText("O");                     
matrix[0][0]=2;                        
 }
else if((matrix[0][0]==1 && matrix[0][1]==0 && matrix[0][2]==1) || (matrix[0][1]==0 && matrix[1][1]==1 && matrix[2][1]==1))//0.1
{
jButton2.setText("O");                     
matrix[0][1]=2;  
}
else if((matrix[0][0]==1 && matrix[0][1]==1 && matrix[0][2]==0) || (matrix[0][2]==0 && matrix[1][2]==1 && matrix[2][2]==1) || (matrix[2][0]==1 && matrix[1][1]==1 && matrix[0][2]==0))//0.2
{
jButton3.setText("O");                     
matrix[0][2]=2;  
}
else if((matrix[1][0]==0 && matrix[1][1]==1 && matrix[1][2]==1) ||(matrix[0][0]==1 && matrix[1][0]==0 && matrix[2][0]==1) )//1.0
{
jButton4.setText("O");                     
matrix[1][0]=2;  
}
else if((matrix[1][0]==1 && matrix[1][1]==0 && matrix[1][2]==1) ||(matrix[0][1]==1 && matrix[1][1]==0 && matrix[2][1]==1) ||(matrix[2][0]==1 && matrix[1][1]==0 && matrix[0][2]==1) ||(matrix[0][0]==1 && matrix[1][1]==0 && matrix[2][2]==1) )//1.1
{
jButton5.setText("O");                     
matrix[1][1]=2;  
}
else if((matrix[1][0]==1 && matrix[1][1]==1 && matrix[1][2]==0) ||(matrix[0][2]==1 && matrix[1][2]==0 && matrix[2][2]==1) )//1.2
{
jButton6.setText("O");                     
matrix[1][2]=2;  
}
else if((matrix[2][0]==0 && matrix[2][1]==1 && matrix[2][2]==1) ||(matrix[0][0]==1 && matrix[1][0]==1 && matrix[2][0]==0) ||(matrix[2][0]==0 && matrix[1][1]==1 && matrix[0][2]==1) )//2.0
{
jButton7.setText("O");                     
matrix[2][0]=2;  
}
else if((matrix[2][0]==1 && matrix[2][1]==0 && matrix[2][2]==1) || (matrix[0][1]==1 && matrix[1][1]==1 && matrix[2][1]==0) )//2.1
{
jButton8.setText("O");                     
matrix[2][1]=2;  
}
else if((matrix[2][0]==1 && matrix[2][1]==1 && matrix[2][2]==0) || (matrix[0][2]==1 && matrix[1][2]==1 && matrix[2][2]==0) || (matrix[0][0]==1 && matrix[1][1]==1 && matrix[2][2]==0) )//2.2
{
jButton9.setText("O");                     
matrix[2][2]=2;  
}
else 
{
while(ban==0)         
{
int posicion = ((int) ( Math.random() * 9 ))+1;         
System.out.println(posicion);
 if (posicion==1)             
{
 if (jButton1.getText()==" ")                 
{                     
jButton1.setText("O");                     
matrix[0][0]=2;                    
 ban=1;                 
}
}             
if (posicion==2)             
{                  
if (jButton2.getText()==" ")                 
{                     
jButton2.setText("O");                     
matrix[0][1]=2;                     
ban=1;                 
}             
}
if (posicion==3)             
{                  
if (jButton3.getText()==" ")                
 {                    
 jButton3.setText("O");                     
matrix[0][2]=2;                     
ban=1;                 
}             
}             
 if (posicion==4)            
 {                  
if (jButton4.getText()==" ")                 
{                     
jButton4.setText("O");                    
 matrix[1][0]=2;                     
ban=1;                 
}            
 }            
 if (posicion==5)            
 {                  
if (jButton5.getText()==" ")                 
{                    
 jButton5.setText("O");                     
matrix[1][1]=2;                     
ban=1;                 
}             
}             
if (posicion==6)            
 {                 
 if (jButton6.getText()==" ")                 
{                     
jButton6.setText("O");                     
matrix[1][2]=2;                     
ban=1;                
 }             
}            
if (posicion==7)             
{
  if (jButton7.getText()==" ")
{                     
jButton7.setText("O");                     
matrix[2][0]=2;                     
ban=1;                 
}             
}             
if (posicion==8)            
 {                  
if (jButton8.getText()==" ")                
 {                     
jButton8.setText("O");                     
matrix[2][1]=2;                     
ban=1;                 
}             
}             
if (posicion==9)             
{                  
if (jButton9.getText()==" ")                
 {                     
jButton9.setText("O");                    
 matrix[2][2]=2;                     
ban=1;                 
} 
}
if ((matrix[0][0]!=0) &&(matrix[0][1]!=0) && (matrix[0][2]!=0) &&
    (matrix[1][0]!=0) &&(matrix[1][1]!=0) && (matrix[1][2]!=0) && 
    (matrix[2][0]!=0) &&(matrix[2][1]!=0) && (matrix[2][2]!=0)) ban=1;         
}  
}
checarJugada();     
} 

private void checarJugada() { 
    int i=0, j=0;
// el jugador  
// las diagonales          
if ((matrix[0][0]==1) &&(matrix[1][1]==1) && (matrix[2][2]==1))              
jTextField1.setText("Ya gaste cuate diagonal");          
else if ((matrix[0][2]==1) &&(matrix[1][1]==1) && (matrix[2][0]==1))              
jTextField1.setText("Ya gaste cuate diagonal");         
// filas          
else if ((matrix[0][0]==1) &&(matrix[0][1]==1) && (matrix[0][2]==1))              
 jTextField1.setText("Ya gaste cuate fila");      
else if ((matrix[1][0]==1) &&(matrix[1][1]==1) && (matrix[1][2]==1))
jTextField1.setText("Ya gaste cuate fila");           
else if ((matrix[2][0]==1) &&(matrix[2][1]==1) && (matrix[2][2]==1))
jTextField1.setText("Ya gaste cuate fila");          
// columnas          
else if ((matrix[0][0]==1) &&(matrix[1][0]==1) && (matrix[2][0]==1))              
jTextField1.setText("Ya gaste cuate columna");        
else if ((matrix[0][1]==1) &&(matrix[1][1]==1) && (matrix[2][1]==1))              
jTextField1.setText("Ya gaste cuate columna");
else if ((matrix[0][2]==1) &&(matrix[1][2]==1) && (matrix[2][2]==1))              
jTextField1.setText("Ya gaste cuate columna");
else i=-1;
// maquina         
// las diagonales          
if ((matrix[0][0]==2) &&(matrix[1][1]==2) && (matrix[2][2]==2))              
jTextField1.setText("Ya PERDISTE cuate diagonal"); 
else if ((matrix[0][2]==2) &&(matrix[1][1]==2) && (matrix[2][0]==2))              
jTextField1.setText("Ya PERDISTE cuate diagonal");          
// filas          
else if ((matrix[0][0]==2) &&(matrix[0][1]==2) && (matrix[0][2]==2))             
 jTextField1.setText("Ya PERDISTE cuate fila"); 
else if ((matrix[1][0]==2) &&(matrix[1][1]==2) && (matrix[1][2]==2))              
 jTextField1.setText("Ya PERDISTE cuate fila"); 
else if ((matrix[2][0]==2) &&(matrix[2][1]==2) && (matrix[2][2]==2))              
jTextField1.setText("Ya PERDISTE cuate fila");        
// columnas          
else if ((matrix[0][0]==2) &&(matrix[1][0]==2) && (matrix[2][0]==2))              
jTextField1.setText("Ya PERDISTE cuate columna"); 
else if ((matrix[0][1]==2) &&(matrix[1][1]==2) && (matrix[2][1]==2))              
jTextField1.setText("Ya PERDISTE cuate columna");         
else if ((matrix[0][2]==2) &&(matrix[1][2]==2) && (matrix[2][2]==2))              
jTextField1.setText("Ya PERDISTE cuate columna"); 
else j=-1;

if ((matrix[0][0]!=0) &&(matrix[0][1]!=0) && (matrix[0][2]!=0) &&
    (matrix[1][0]!=0) &&(matrix[1][1]!=0) && (matrix[1][2]!=0) && 
    (matrix[2][0]!=0) &&(matrix[2][1]!=0) && (matrix[2][2]!=0) && i==-1 && j==-1)
    jTextField1.setText("empate");
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantallagato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantallagato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantallagato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantallagato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantallagato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
